@HostAddress = https://localhost:7077
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJoZWluQHRlc3QuY29tIiwiaWF0IjoxNzI2ODc1NzMxLCJleHAiOjE3MjY4NzkzMzEsIm5iZiI6MTcyNjg3NTczMX0.CrTJFAmAkT1QJmvTuyAzwOtR8ISr_xOmtwRdBYoIC6w

###
#LOGIN
POST {{HostAddress}}/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "hein@test.com",
  "password": "Password@123"
}

### 
#Add Cart Item

POST {{HostAddress}}/api/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bookId": "00000000-0000-0000-0000-000000000002",
  "quantity": 1
}

###
#Get Cart Items
GET {{HostAddress}}/api/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{HostAddress}}/api/cart/checkout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "shippingAddressId": "00000000-0000-0000-0000-000000000002",
  "billingAddressId": "00000000-0000-0000-0000-000000000002"
}