@HostAddress = https://localhost:7077
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJoZWluQHRlc3QuY29tIiwiaWF0IjoxNzI1OTQ5NDM1LCJleHAiOjE3MjU5NTMwMzUsIm5iZiI6MTcyNTk0OTQzNX0.tWjIh2QNa7b77ErZNRrMrlZYjnyGXAGc7r7EmuEy8LQ

###
#LOGIN
POST {{HostAddress}}/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "hein@test.com",
  "password": "Password@123"
}

### 
#Add Cart Item

POST {{HostAddress}}/api/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bookId": "00000000-0000-0000-0000-000000000002",
  "quantity": 1
}

###
#Get Cart Items
GET {{HostAddress}}/api/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
